// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/4udiwe/cowoking/booking-service/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
	isgomock struct{}
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockBookingRepository) Cancel(ctx context.Context, id uuid.UUID, reason *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockBookingRepositoryMockRecorder) Cancel(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockBookingRepository)(nil).Cancel), ctx, id, reason)
}

// Create mocks base method.
func (m *MockBookingRepository) Create(ctx context.Context, booking entity.Booking) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, booking)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBookingRepositoryMockRecorder) Create(ctx, booking any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookingRepository)(nil).Create), ctx, booking)
}

// GetAdminActiveBookings mocks base method.
func (m *MockBookingRepository) GetAdminActiveBookings(ctx context.Context, coworkingID uuid.UUID, page, pageSize int, dateFrom, dateTo *time.Time, placeType, sortBy *string) ([]entity.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminActiveBookings", ctx, coworkingID, page, pageSize, dateFrom, dateTo, placeType, sortBy)
	ret0, _ := ret[0].([]entity.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAdminActiveBookings indicates an expected call of GetAdminActiveBookings.
func (mr *MockBookingRepositoryMockRecorder) GetAdminActiveBookings(ctx, coworkingID, page, pageSize, dateFrom, dateTo, placeType, sortBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminActiveBookings", reflect.TypeOf((*MockBookingRepository)(nil).GetAdminActiveBookings), ctx, coworkingID, page, pageSize, dateFrom, dateTo, placeType, sortBy)
}

// GetByID mocks base method.
func (m *MockBookingRepository) GetByID(ctx context.Context, id uuid.UUID) (entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBookingRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBookingRepository)(nil).GetByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockBookingRepository) ListByUser(ctx context.Context, userID uuid.UUID, page, pageSize int, status *string) ([]entity.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, page, pageSize, status)
	ret0, _ := ret[0].([]entity.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockBookingRepositoryMockRecorder) ListByUser(ctx, userID, page, pageSize, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockBookingRepository)(nil).ListByUser), ctx, userID, page, pageSize, status)
}

// MarkCompleted mocks base method.
func (m *MockBookingRepository) MarkCompleted(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCompleted", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCompleted indicates an expected call of MarkCompleted.
func (mr *MockBookingRepositoryMockRecorder) MarkCompleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompleted", reflect.TypeOf((*MockBookingRepository)(nil).MarkCompleted), ctx, id)
}

// MockPlaceRepository is a mock of PlaceRepository interface.
type MockPlaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlaceRepositoryMockRecorder
	isgomock struct{}
}

// MockPlaceRepositoryMockRecorder is the mock recorder for MockPlaceRepository.
type MockPlaceRepositoryMockRecorder struct {
	mock *MockPlaceRepository
}

// NewMockPlaceRepository creates a new mock instance.
func NewMockPlaceRepository(ctrl *gomock.Controller) *MockPlaceRepository {
	mock := &MockPlaceRepository{ctrl: ctrl}
	mock.recorder = &MockPlaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaceRepository) EXPECT() *MockPlaceRepositoryMockRecorder {
	return m.recorder
}

// CheckHasActiveBookings mocks base method.
func (m *MockPlaceRepository) CheckHasActiveBookings(ctx context.Context, placeID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHasActiveBookings", ctx, placeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckHasActiveBookings indicates an expected call of CheckHasActiveBookings.
func (mr *MockPlaceRepositoryMockRecorder) CheckHasActiveBookings(ctx, placeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHasActiveBookings", reflect.TypeOf((*MockPlaceRepository)(nil).CheckHasActiveBookings), ctx, placeID)
}

// CreateBatch mocks base method.
func (m *MockPlaceRepository) CreateBatch(ctx context.Context, places []entity.Place) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, places)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockPlaceRepositoryMockRecorder) CreateBatch(ctx, places any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockPlaceRepository)(nil).CreateBatch), ctx, places)
}

// GetAvailableByCoworking mocks base method.
func (m *MockPlaceRepository) GetAvailableByCoworking(ctx context.Context, coworkingID uuid.UUID, start, end time.Time) ([]entity.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableByCoworking", ctx, coworkingID, start, end)
	ret0, _ := ret[0].([]entity.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableByCoworking indicates an expected call of GetAvailableByCoworking.
func (mr *MockPlaceRepositoryMockRecorder) GetAvailableByCoworking(ctx, coworkingID, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableByCoworking", reflect.TypeOf((*MockPlaceRepository)(nil).GetAvailableByCoworking), ctx, coworkingID, start, end)
}

// GetByCoworking mocks base method.
func (m *MockPlaceRepository) GetByCoworking(ctx context.Context, coworkingID uuid.UUID) ([]entity.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCoworking", ctx, coworkingID)
	ret0, _ := ret[0].([]entity.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCoworking indicates an expected call of GetByCoworking.
func (mr *MockPlaceRepositoryMockRecorder) GetByCoworking(ctx, coworkingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCoworking", reflect.TypeOf((*MockPlaceRepository)(nil).GetByCoworking), ctx, coworkingID)
}

// GetByID mocks base method.
func (m *MockPlaceRepository) GetByID(ctx context.Context, id uuid.UUID) (entity.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPlaceRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPlaceRepository)(nil).GetByID), ctx, id)
}

// SetActive mocks base method.
func (m *MockPlaceRepository) SetActive(ctx context.Context, id uuid.UUID, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockPlaceRepositoryMockRecorder) SetActive(ctx, id, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockPlaceRepository)(nil).SetActive), ctx, id, active)
}

// MockCoworkingRepository is a mock of CoworkingRepository interface.
type MockCoworkingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCoworkingRepositoryMockRecorder
	isgomock struct{}
}

// MockCoworkingRepositoryMockRecorder is the mock recorder for MockCoworkingRepository.
type MockCoworkingRepositoryMockRecorder struct {
	mock *MockCoworkingRepository
}

// NewMockCoworkingRepository creates a new mock instance.
func NewMockCoworkingRepository(ctrl *gomock.Controller) *MockCoworkingRepository {
	mock := &MockCoworkingRepository{ctrl: ctrl}
	mock.recorder = &MockCoworkingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoworkingRepository) EXPECT() *MockCoworkingRepositoryMockRecorder {
	return m.recorder
}

// CheckHasActiveBookings mocks base method.
func (m *MockCoworkingRepository) CheckHasActiveBookings(ctx context.Context, coworkingID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHasActiveBookings", ctx, coworkingID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckHasActiveBookings indicates an expected call of CheckHasActiveBookings.
func (mr *MockCoworkingRepositoryMockRecorder) CheckHasActiveBookings(ctx, coworkingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHasActiveBookings", reflect.TypeOf((*MockCoworkingRepository)(nil).CheckHasActiveBookings), ctx, coworkingID)
}

// Create mocks base method.
func (m *MockCoworkingRepository) Create(ctx context.Context, coworking entity.Coworking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, coworking)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCoworkingRepositoryMockRecorder) Create(ctx, coworking any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCoworkingRepository)(nil).Create), ctx, coworking)
}

// CreateLayoutVersion mocks base method.
func (m *MockCoworkingRepository) CreateLayoutVersion(ctx context.Context, layout entity.CoworkingLayout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLayoutVersion", ctx, layout)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLayoutVersion indicates an expected call of CreateLayoutVersion.
func (mr *MockCoworkingRepositoryMockRecorder) CreateLayoutVersion(ctx, layout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLayoutVersion", reflect.TypeOf((*MockCoworkingRepository)(nil).CreateLayoutVersion), ctx, layout)
}

// DeleteLayoutVersion mocks base method.
func (m *MockCoworkingRepository) DeleteLayoutVersion(ctx context.Context, coworkingID uuid.UUID, layoutVersion int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLayoutVersion", ctx, coworkingID, layoutVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLayoutVersion indicates an expected call of DeleteLayoutVersion.
func (mr *MockCoworkingRepositoryMockRecorder) DeleteLayoutVersion(ctx, coworkingID, layoutVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLayoutVersion", reflect.TypeOf((*MockCoworkingRepository)(nil).DeleteLayoutVersion), ctx, coworkingID, layoutVersion)
}

// DisableAllLayoutsByCoworking mocks base method.
func (m *MockCoworkingRepository) DisableAllLayoutsByCoworking(ctx context.Context, coworkingID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableAllLayoutsByCoworking", ctx, coworkingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableAllLayoutsByCoworking indicates an expected call of DisableAllLayoutsByCoworking.
func (mr *MockCoworkingRepositoryMockRecorder) DisableAllLayoutsByCoworking(ctx, coworkingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableAllLayoutsByCoworking", reflect.TypeOf((*MockCoworkingRepository)(nil).DisableAllLayoutsByCoworking), ctx, coworkingID)
}

// GetActiveLayout mocks base method.
func (m *MockCoworkingRepository) GetActiveLayout(ctx context.Context, coworkingID uuid.UUID) (entity.CoworkingLayout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveLayout", ctx, coworkingID)
	ret0, _ := ret[0].(entity.CoworkingLayout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveLayout indicates an expected call of GetActiveLayout.
func (mr *MockCoworkingRepositoryMockRecorder) GetActiveLayout(ctx, coworkingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveLayout", reflect.TypeOf((*MockCoworkingRepository)(nil).GetActiveLayout), ctx, coworkingID)
}

// GetByID mocks base method.
func (m *MockCoworkingRepository) GetByID(ctx context.Context, id uuid.UUID) (entity.Coworking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Coworking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCoworkingRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCoworkingRepository)(nil).GetByID), ctx, id)
}

// GetLayoutByVersion mocks base method.
func (m *MockCoworkingRepository) GetLayoutByVersion(ctx context.Context, coworkingID uuid.UUID, version int) (entity.CoworkingLayout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLayoutByVersion", ctx, coworkingID, version)
	ret0, _ := ret[0].(entity.CoworkingLayout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLayoutByVersion indicates an expected call of GetLayoutByVersion.
func (mr *MockCoworkingRepositoryMockRecorder) GetLayoutByVersion(ctx, coworkingID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLayoutByVersion", reflect.TypeOf((*MockCoworkingRepository)(nil).GetLayoutByVersion), ctx, coworkingID, version)
}

// List mocks base method.
func (m *MockCoworkingRepository) List(ctx context.Context) ([]entity.Coworking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Coworking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCoworkingRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCoworkingRepository)(nil).List), ctx)
}

// ListLayoutVersions mocks base method.
func (m *MockCoworkingRepository) ListLayoutVersions(ctx context.Context, coworkingID uuid.UUID) ([]entity.CoworkingLayoutVersionTime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLayoutVersions", ctx, coworkingID)
	ret0, _ := ret[0].([]entity.CoworkingLayoutVersionTime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLayoutVersions indicates an expected call of ListLayoutVersions.
func (mr *MockCoworkingRepositoryMockRecorder) ListLayoutVersions(ctx, coworkingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLayoutVersions", reflect.TypeOf((*MockCoworkingRepository)(nil).ListLayoutVersions), ctx, coworkingID)
}

// SetActive mocks base method.
func (m *MockCoworkingRepository) SetActive(ctx context.Context, id uuid.UUID, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockCoworkingRepositoryMockRecorder) SetActive(ctx, id, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockCoworkingRepository)(nil).SetActive), ctx, id, active)
}

// SetLayoutActiveByVersion mocks base method.
func (m *MockCoworkingRepository) SetLayoutActiveByVersion(ctx context.Context, coworkingID uuid.UUID, layoutVersion int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLayoutActiveByVersion", ctx, coworkingID, layoutVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLayoutActiveByVersion indicates an expected call of SetLayoutActiveByVersion.
func (mr *MockCoworkingRepositoryMockRecorder) SetLayoutActiveByVersion(ctx, coworkingID, layoutVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLayoutActiveByVersion", reflect.TypeOf((*MockCoworkingRepository)(nil).SetLayoutActiveByVersion), ctx, coworkingID, layoutVersion)
}

// Update mocks base method.
func (m *MockCoworkingRepository) Update(ctx context.Context, coworking entity.Coworking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, coworking)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCoworkingRepositoryMockRecorder) Update(ctx, coworking any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCoworkingRepository)(nil).Update), ctx, coworking)
}

// MockOutboxRepo is a mock of OutboxRepo interface.
type MockOutboxRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepoMockRecorder
	isgomock struct{}
}

// MockOutboxRepoMockRecorder is the mock recorder for MockOutboxRepo.
type MockOutboxRepoMockRecorder struct {
	mock *MockOutboxRepo
}

// NewMockOutboxRepo creates a new mock instance.
func NewMockOutboxRepo(ctrl *gomock.Controller) *MockOutboxRepo {
	mock := &MockOutboxRepo{ctrl: ctrl}
	mock.recorder = &MockOutboxRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepo) EXPECT() *MockOutboxRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOutboxRepo) Create(ctx context.Context, ev entity.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboxRepoMockRecorder) Create(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxRepo)(nil).Create), ctx, ev)
}
